"""
Script to create notebooks/05_task4_cgan_sketch.ipynb with robust Colab execution:
- Git clone repo for code imports with persistent sys.path and chdir
- Direct-to-Drive and local dual-checkpointing for survival across kernel/runtime resets
- Auto-recovery of Optuna best_params from Drive/local JSON in Steps 6, 7, 8, 9
- Strict checkpoint loading with clear logging (raises if missing or mismatched)
- Fast local NVMe caching for FS2K dataset
- Optuna study (15 trials, 10 epochs/trial)
- Full 40-epoch training schedule with sample visual grids and D throttling
- Style-stratified evaluation on test set (Styles 0, 1, 2, Overall)
- Generator-only ONNX export & parity check (opset 18, embedded weights)
- Comprehensive Drive synchronization and verification
"""

import json
import os

def build_task4_notebook():
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Task 4: Style-Conditioned Face-to-Sketch Generation Using a Conditional GAN\n",
                "**Dataset:** FS2K Facial Sketch Synthesis Dataset (899 train / 159 val / 1,046 test pairs stratified by style 0, 1, 2)\n",
                "**Architecture:** U-Net Generator with full skip connections at all levels + 70x70 PatchGAN Discriminator with categorical style embedding conditioning\n",
                "**Loss Function:** $\\mathcal{L}_{\\text{cGAN}} = \\mathcal{L}_{\\text{adv}}(G, D) + \\lambda_{\\text{L1}} \\mathcal{L}_{\\text{L1}}(G)$\n",
                "**Optimization:** 15-Trial Optuna Study tuning $\\text{lr}_g, \\text{lr}_d, \\lambda_{\\text{L1}}$, base channels, emb dim, and dropout rate."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 1: Environment Diagnostics & GPU Verification"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch\n",
                "import os\n",
                "import sys\n",
                "import subprocess\n",
                "\n",
                "print(f\"PyTorch Version: {torch.__version__}\")\n",
                "print(f\"CUDA Available: {torch.cuda.is_available()}\")\n",
                "if torch.cuda.is_available():\n",
                "    print(f\"GPU Device: {torch.cuda.get_device_name(0)}\")\n",
                "    print(f\"VRAM: {torch.cuda.get_device_properties(0).total_memory / (1024**3):.2f} GB\")\n",
                "else:\n",
                "    print(\"WARNING: Running on CPU. Switch to GPU runtime for reasonable training speeds!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 2: Mount Google Drive & Clone/Pull GitHub Repository"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "import subprocess\n",
                "\n",
                "# Mount Drive for data and checkpoint persistence\n",
                "try:\n",
                "    from google.colab import drive\n",
                "    drive.mount('/content/drive')\n",
                "except Exception:\n",
                "    print(\"Google Drive mounting skipped (not running in Colab).\")\n",
                "\n",
                "REPO_DIR = '/content/genai-restoration-studio'\n",
                "PROJECT_DIR = '/content/drive/MyDrive/GenAI-A1'\n",
                "\n",
                "# Clone or pull repository\n",
                "if not os.path.exists(REPO_DIR):\n",
                "    print(f\"Cloning repo into {REPO_DIR}...\")\n",
                "    subprocess.run([\"git\", \"clone\", \"https://github.com/UsmanBari/genai-restoration-studio.git\", REPO_DIR], check=True)\n",
                "else:\n",
                "    print(f\"Pulling latest main into {REPO_DIR}...\")\n",
                "    subprocess.run([\"git\", \"-C\", REPO_DIR, \"pull\", \"origin\", \"main\"], check=True)\n",
                "\n",
                "if REPO_DIR not in sys.path:\n",
                "    sys.path.insert(0, REPO_DIR)\n",
                "\n",
                "os.chdir(REPO_DIR)\n",
                "print(f\"Working directory: {os.getcwd()}\")\n",
                "\n",
                "# Install requirements\n",
                "subprocess.run([sys.executable, \"-m\", \"pip\", \"install\", \"-q\", \"onnx\", \"onnxruntime\", \"optuna\", \"mlflow\"], check=False)\n",
                "print(\"[SUCCESS] Environment and repository ready.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 3: Fast Local NVMe Caching & Dataset Preparation (FS2K)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import shutil\n",
                "import json\n",
                "import os\n",
                "import sys\n",
                "import zipfile\n",
                "\n",
                "REPO_DIR = '/content/genai-restoration-studio' if os.path.exists('/content/genai-restoration-studio') else os.getcwd()\n",
                "PROJECT_DIR = '/content/drive/MyDrive/GenAI-A1'\n",
                "if REPO_DIR not in sys.path:\n",
                "    sys.path.insert(0, REPO_DIR)\n",
                "os.chdir(REPO_DIR)\n",
                "\n",
                "from data.fs2k import FS2KDataset, get_fs2k_dataloaders\n",
                "\n",
                "LOCAL_DATA_DIR = '/content/local_data/FS2K'\n",
                "os.makedirs(LOCAL_DATA_DIR, exist_ok=True)\n",
                "\n",
                "# Candidate zip locations in Drive\n",
                "drive_zip_candidates = [\n",
                "    os.path.join(PROJECT_DIR, 'raw/FS2K.zip'),\n",
                "    os.path.join(PROJECT_DIR, 'raw/FS2K/FS2K.zip'),\n",
                "    os.path.join(PROJECT_DIR, 'FS2K.zip'),\n",
                "    os.path.join(PROJECT_DIR, 'data/FS2K.zip')\n",
                "]\n",
                "\n",
                "drive_folder_candidates = [\n",
                "    os.path.join(PROJECT_DIR, 'raw/FS2K/FS2K'),\n",
                "    os.path.join(PROJECT_DIR, 'raw/FS2K'),\n",
                "    os.path.join(PROJECT_DIR, 'data/FS2K')\n",
                "]\n",
                "\n",
                "# Check if already extracted locally\n",
                "if not os.path.exists(os.path.join(LOCAL_DATA_DIR, 'photo')):\n",
                "    zip_found = None\n",
                "    for zc in drive_zip_candidates:\n",
                "        if os.path.exists(zc):\n",
                "            zip_found = zc\n",
                "            break\n",
                "    \n",
                "    if zip_found:\n",
                "        print(f\"Extracting FS2K dataset from {zip_found} to {LOCAL_DATA_DIR}...\")\n",
                "        with zipfile.ZipFile(zip_found, 'r') as zf:\n",
                "            zf.extractall('/content/local_data/')\n",
                "        nested = '/content/local_data/FS2K/FS2K'\n",
                "        if os.path.exists(nested):\n",
                "            for item in os.listdir(nested):\n",
                "                shutil.move(os.path.join(nested, item), os.path.join(LOCAL_DATA_DIR, item))\n",
                "    else:\n",
                "        # Check if extracted folder exists on Drive\n",
                "        folder_found = None\n",
                "        for fc in drive_folder_candidates:\n",
                "            if os.path.exists(os.path.join(fc, 'photo')):\n",
                "                folder_found = fc\n",
                "                break\n",
                "        if folder_found:\n",
                "            print(f\"Copying FS2K folder from {folder_found} to local NVMe {LOCAL_DATA_DIR}...\")\n",
                "            for item in os.listdir(folder_found):\n",
                "                s = os.path.join(folder_found, item)\n",
                "                d = os.path.join(LOCAL_DATA_DIR, item)\n",
                "                if os.path.isdir(s):\n",
                "                    shutil.copytree(s, d, dirs_exist_ok=True)\n",
                "                else:\n",
                "                    shutil.copy2(s, d)\n",
                "        else:\n",
                "            print(\"Using direct FS2K root resolution from manifests.\")\n",
                "\n",
                "# Manifest directory resolution: Prioritize authentic Drive manifests from colab bootstrap\n",
                "manifest_candidates = [\n",
                "    os.path.join(PROJECT_DIR, 'manifests'),\n",
                "    os.path.join(PROJECT_DIR, 'configs/manifests'),\n",
                "    os.path.join(REPO_DIR, 'configs/manifests'),\n",
                "    os.path.join(REPO_DIR, 'manifests')\n",
                "]\n",
                "MANIFEST_DIR = None\n",
                "for mc in manifest_candidates:\n",
                "    if os.path.exists(os.path.join(mc, 'fs2k_train_manifest.json')):\n",
                "        MANIFEST_DIR = mc\n",
                "        break\n",
                "\n",
                "if MANIFEST_DIR is None:\n",
                "    raise FileNotFoundError(\"FS2K train manifest not found in Drive or repo!\")\n",
                "\n",
                "print(f\"Manifest Directory Used: {MANIFEST_DIR}\")\n",
                "\n",
                "# Load and verify authentic manifest counts and style distribution\n",
                "from collections import Counter\n",
                "with open(os.path.join(MANIFEST_DIR, 'fs2k_train_manifest.json'), 'r', encoding='utf-8') as f:\n",
                "    train_data = json.load(f)\n",
                "with open(os.path.join(MANIFEST_DIR, 'fs2k_val_manifest.json'), 'r', encoding='utf-8') as f:\n",
                "    val_data = json.load(f)\n",
                "with open(os.path.join(MANIFEST_DIR, 'fs2k_test_manifest.json'), 'r', encoding='utf-8') as f:\n",
                "    test_data = json.load(f)\n",
                "\n",
                "train_styles = Counter(x['style'] for x in train_data)\n",
                "val_styles = Counter(x['style'] for x in val_data)\n",
                "test_styles = Counter(x['style'] for x in test_data)\n",
                "\n",
                "print(f\"Train Pairs: {len(train_data)} | Style Distribution: {dict(train_styles)}\")\n",
                "print(f\"Val Pairs:   {len(val_data)} | Style Distribution: {dict(val_styles)}\")\n",
                "print(f\"Test Pairs:  {len(test_data)} | Style Distribution: {dict(test_styles)}\")\n",
                "\n",
                "# Strict assertions enforcing authentic FS2K splits\n",
                "assert len(train_data) == 898, f\"Expected 898 train pairs, got {len(train_data)}\"\n",
                "assert len(val_data) == 160, f\"Expected 160 val pairs, got {len(val_data)}\"\n",
                "assert len(test_data) == 1046, f\"Expected 1046 test pairs, got {len(test_data)}\"\n",
                "assert dict(train_styles) == {0: 303, 1: 297, 2: 298}, f\"Train style mismatch: {dict(train_styles)}\"\n",
                "assert dict(val_styles) == {0: 54, 1: 53, 2: 53}, f\"Val style mismatch: {dict(val_styles)}\"\n",
                "assert dict(test_styles) == {0: 619, 1: 381, 2: 46} or dict(test_styles) == {1: 381, 0: 619, 2: 46}, f\"Test style mismatch: {dict(test_styles)}\"\n",
                "print(\"✅ Authentic FS2K dataset split verified: 898 train / 160 val / 1,046 test.\")\n",
                "\n",
                "# Build DataLoaders\n",
                "train_loader, val_loader, test_loader = get_fs2k_dataloaders(\n",
                "    manifest_dir=MANIFEST_DIR,\n",
                "    fs2k_root=LOCAL_DATA_DIR,\n",
                "    batch_size=16,\n",
                "    num_workers=0\n",
                ")\n",
                "\n",
                "print(f\"Train batches: {len(train_loader)} ({len(train_loader.dataset)} pairs)\")\n",
                "print(f\"Val batches:   {len(val_loader)} ({len(val_loader.dataset)} pairs)\")\n",
                "print(f\"Test batches:  {len(test_loader)} ({len(test_loader.dataset)} pairs)\")\n",
                "\n",
                "# Pre-flight Check 1: Exhaustive file existence verification using dataset's own path resolver\n",
                "print(\"Running pre-flight verification: checking disk existence for all 2,104 photo/sketch pairs via dataset resolver...\")\n",
                "for name, ld in [('train', train_loader), ('val', val_loader), ('test', test_loader)]:\n",
                "    ds = ld.dataset\n",
                "    for idx, it in enumerate(ds.items):\n",
                "        p_path, s_path = ds._resolve_paths(it)\n",
                "        if not os.path.exists(p_path) or not os.path.exists(s_path):\n",
                "            raise FileNotFoundError(f\"[{name} item {idx}] Missing file! Photo ({os.path.exists(p_path)}): {p_path}, Sketch ({os.path.exists(s_path)}): {s_path}\")\n",
                "print(\"✅ Pre-flight Check 1 PASSED: 100% of 2,104 photo/sketch pairs resolved and verified on disk!\")\n",
                "\n",
                "# Pre-flight Check 2: Verify zero flat/placeholder samples across all loaders\n",
                "def flat_samples(ds, name):\n",
                "    bad = []\n",
                "    for i in range(len(ds)):\n",
                "        s = ds[i]\n",
                "        vals = s.values() if isinstance(s, dict) else s\n",
                "        ts = [v for v in vals if torch.is_tensor(v) and v.dim() == 3]\n",
                "        if any(float(t.float().std()) < 1e-3 for t in ts):\n",
                "            bad.append(i)\n",
                "    print(f\"{name}: {len(ds)} samples, flat/placeholder images: {len(bad)}\")\n",
                "    assert len(bad) == 0, f\"Found {len(bad)} flat/placeholder images in {name} dataset!\"\n",
                "    return bad\n",
                "\n",
                "for name, ld in [('train', train_loader), ('val', val_loader), ('test', test_loader)]:\n",
                "    flat_samples(ld.dataset, name)\n",
                "print(\"✅ Pre-flight Check 2 PASSED: Zero flat or placeholder images detected across train/val/test loaders!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 4: Baseline Model Sanity Check (U-Net Generator & PatchGAN Discriminator)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from models.cgan import StyleConditionedUNetGenerator, ConditionalPatchGANDiscriminator\n",
                "from training.losses_cgan import ConditionalGANLoss\n",
                "\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f\"Using device: {device}\")\n",
                "\n",
                "dummy_g = StyleConditionedUNetGenerator().to(device)\n",
                "dummy_d = ConditionalPatchGANDiscriminator().to(device)\n",
                "criterion = ConditionalGANLoss(lambda_l1=100.0)\n",
                "\n",
                "batch = next(iter(train_loader))\n",
                "p = batch['photo'].to(device)\n",
                "s = batch['sketch'].to(device)\n",
                "st = batch['style'].to(device)\n",
                "\n",
                "fake = dummy_g(p, st)\n",
                "d_real = dummy_d(p, s, st)\n",
                "d_fake = dummy_d(p, fake.detach(), st)\n",
                "\n",
                "loss_d, m_d = criterion.discriminator_loss(d_real, d_fake)\n",
                "loss_g, m_g = criterion.generator_loss(dummy_d(p, fake, st), fake, s)\n",
                "\n",
                "print(f\"Generator Output Shape:     {fake.shape} (Range: [{fake.min():.2f}, {fake.max():.2f}])\")\n",
                "print(f\"Discriminator Patch Logits: {d_real.shape}\")\n",
                "print(f\"Loss D: {loss_d.item():.4f} (Real Acc: {m_d['d_acc_real']*100:.1f}%, Fake Acc: {m_d['d_acc_fake']*100:.1f}%)\")\n",
                "print(f\"Loss G: {loss_g.item():.4f} (Adv: {m_g['loss_g_adv']:.4f}, L1: {m_g['loss_g_l1']:.4f})\")\n",
                "print(\"[SUCCESS] Baseline cGAN sanity check passed.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 5: 15-Trial Optuna Hyperparameter Optimization Study"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "import json\n",
                "import torch\n",
                "\n",
                "REPO_DIR = '/content/genai-restoration-studio' if os.path.exists('/content/genai-restoration-studio') else os.getcwd()\n",
                "PROJECT_DIR = '/content/drive/MyDrive/GenAI-A1'\n",
                "if REPO_DIR not in sys.path:\n",
                "    sys.path.insert(0, REPO_DIR)\n",
                "os.chdir(REPO_DIR)\n",
                "\n",
                "from training.optuna_cgan import run_optuna_cgan_study\n",
                "\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "\n",
                "study = run_optuna_cgan_study(\n",
                "    train_loader=train_loader,\n",
                "    val_loader=val_loader,\n",
                "    device=device,\n",
                "    n_trials=15,\n",
                "    epochs_per_trial=10,\n",
                "    study_name=\"task4_cgan_fs2k_study\"\n",
                ")\n",
                "\n",
                "best_params = study.best_params\n",
                "print(\"\\nWinning Optuna Hyperparameters:\")\n",
                "for k, v in best_params.items():\n",
                "    print(f\"  {k}: {v}\")\n",
                "\n",
                "# Persist best_params to both local repo and Google Drive immediately\n",
                "local_optuna_path = os.path.join(REPO_DIR, 'checkpoints/task4/optuna_best_params.json')\n",
                "drive_optuna_path = os.path.join(PROJECT_DIR, 'checkpoints/task4/optuna_best_params.json')\n",
                "\n",
                "os.makedirs(os.path.dirname(local_optuna_path), exist_ok=True)\n",
                "try:\n",
                "    os.makedirs(os.path.dirname(drive_optuna_path), exist_ok=True)\n",
                "except Exception:\n",
                "    pass\n",
                "\n",
                "with open(local_optuna_path, 'w', encoding='utf-8') as f:\n",
                "    json.dump(best_params, f, indent=2)\n",
                "\n",
                "try:\n",
                "    with open(drive_optuna_path, 'w', encoding='utf-8') as f:\n",
                "        json.dump(best_params, f, indent=2)\n",
                "    print(f\"[SUCCESS] Saved Optuna best parameters to Google Drive at {drive_optuna_path}\")\n",
                "except Exception as e:\n",
                "    print(f\"[WARNING] Could not save best_params to Drive: {e}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 6: Full Schedule 40-Epoch Training of Optimal cGAN Model"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "import json\n",
                "import shutil\n",
                "import torch\n",
                "from torch.utils.data import DataLoader\n",
                "\n",
                "REPO_DIR = '/content/genai-restoration-studio' if os.path.exists('/content/genai-restoration-studio') else os.getcwd()\n",
                "PROJECT_DIR = '/content/drive/MyDrive/GenAI-A1'\n",
                "if REPO_DIR not in sys.path:\n",
                "    sys.path.insert(0, REPO_DIR)\n",
                "os.chdir(REPO_DIR)\n",
                "\n",
                "from models.cgan import StyleConditionedUNetGenerator, ConditionalPatchGANDiscriminator\n",
                "from training.trainer_cgan import train_cgan_full\n",
                "from data.fs2k import get_fs2k_dataloaders\n",
                "\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f\"Using device: {device}\")\n",
                "\n",
                "# Recover best_params if missing from memory\n",
                "if 'best_params' not in globals() or not best_params:\n",
                "    optuna_paths = [\n",
                "        os.path.join(PROJECT_DIR, 'checkpoints/task4/optuna_best_params.json'),\n",
                "        os.path.join(REPO_DIR, 'checkpoints/task4/optuna_best_params.json')\n",
                "    ]\n",
                "    loaded_params = None\n",
                "    for op in optuna_paths:\n",
                "        if os.path.exists(op):\n",
                "            with open(op, 'r', encoding='utf-8') as f:\n",
                "                loaded_params = json.load(f)\n",
                "            print(f\"[RECOVERY] Loaded Optuna parameters from {op}\")\n",
                "            break\n",
                "    if loaded_params is None:\n",
                "        print(\"[WARNING] No saved Optuna parameters found. Falling back to baseline configuration.\")\n",
                "        loaded_params = {\n",
                "            'lr_g': 0.0004,\n",
                "            'lr_d': 0.00008,\n",
                "            'batch_size': 16,\n",
                "            'lambda_l1': 100.0,\n",
                "            'base_channels_g': 64,\n",
                "            'emb_dim': 32,\n",
                "            'dropout_rate': 0.5\n",
                "        }\n",
                "    best_params = loaded_params\n",
                "\n",
                "# Ensure dataloaders exist\n",
                "if 'train_loader' not in globals() or 'val_loader' not in globals():\n",
                "    manifest_candidates = [\n",
                "        os.path.join(PROJECT_DIR, 'manifests'),\n",
                "        os.path.join(PROJECT_DIR, 'configs/manifests'),\n",
                "        os.path.join(REPO_DIR, 'configs/manifests'),\n",
                "        os.path.join(REPO_DIR, 'manifests')\n",
                "    ]\n",
                "    m_dir = next(mc for mc in manifest_candidates if os.path.exists(os.path.join(mc, 'fs2k_train_manifest.json')))\n",
                "    local_data = '/content/local_data/FS2K' if os.path.exists('/content/local_data/FS2K') else os.path.join(PROJECT_DIR, 'raw/FS2K/FS2K')\n",
                "    train_loader, val_loader, test_loader = get_fs2k_dataloaders(m_dir, local_data, batch_size=16, num_workers=0)\n",
                "\n",
                "# Rebuild train_loader with optimal batch size from Optuna\n",
                "opt_bs = int(best_params.get('batch_size', 16))\n",
                "opt_train_loader = DataLoader(train_loader.dataset, batch_size=opt_bs, shuffle=True, num_workers=0)\n",
                "\n",
                "# Instantiate models with optimal Optuna parameters\n",
                "best_g = StyleConditionedUNetGenerator(\n",
                "    in_channels=3,\n",
                "    out_channels=3,\n",
                "    num_styles=3,\n",
                "    emb_dim=int(best_params.get('emb_dim', 32)),\n",
                "    emb_channels=16,\n",
                "    base_channels=int(best_params.get('base_channels_g', 64)),\n",
                "    dropout_rate=float(best_params.get('dropout_rate', 0.5))\n",
                ").to(device)\n",
                "\n",
                "best_d = ConditionalPatchGANDiscriminator(\n",
                "    in_channels=3,\n",
                "    num_styles=3,\n",
                "    emb_dim=int(best_params.get('emb_dim', 32)),\n",
                "    emb_channels=16,\n",
                "    base_channels=64\n",
                ").to(device)\n",
                "\n",
                "save_dir = os.path.join(REPO_DIR, 'checkpoints/task4')\n",
                "drive_save_dir = os.path.join(PROJECT_DIR, 'checkpoints/task4')\n",
                "os.makedirs(save_dir, exist_ok=True)\n",
                "try:\n",
                "    os.makedirs(drive_save_dir, exist_ok=True)\n",
                "except Exception:\n",
                "    pass\n",
                "\n",
                "# Rebalancing: enforce 0.2x D/G learning rate ratio and D throttling\n",
                "opt_lr_g = float(best_params.get('lr_g', 4e-4))\n",
                "opt_lr_d = opt_lr_g * 0.2\n",
                "print(f\"Rebalanced Learning Rates: G={opt_lr_g:.2e}, D={opt_lr_d:.2e} (D/G ratio: {opt_lr_d/opt_lr_g:.2f})\")\n",
                "\n",
                "training_results = train_cgan_full(\n",
                "    net_g=best_g,\n",
                "    net_d=best_d,\n",
                "    train_loader=opt_train_loader,\n",
                "    val_loader=val_loader,\n",
                "    device=device,\n",
                "    save_dir=save_dir,\n",
                "    drive_save_dir=drive_save_dir,\n",
                "    epochs=40,\n",
                "    lr_g=opt_lr_g,\n",
                "    lr_d=opt_lr_d,\n",
                "    lambda_l1=float(best_params.get('lambda_l1', 100.0)),\n",
                "    d_update_freq=2,\n",
                "    d_max_acc_throttle=0.85,\n",
                "    patience=8,\n",
                "    experiment_name=\"Task4_cGAN_FS2K_Full\"\n",
                ")\n",
                "\n",
                "# Confirm checkpoint persistence to Drive\n",
                "if os.path.exists(save_dir) and os.path.exists(drive_save_dir):\n",
                "    for f in os.listdir(save_dir):\n",
                "        s_path = os.path.join(save_dir, f)\n",
                "        d_path = os.path.join(drive_save_dir, f)\n",
                "        if os.path.isfile(s_path):\n",
                "            shutil.copy2(s_path, d_path)\n",
                "print(f\"[SUCCESS] Checkpoint synchronized to Drive: {drive_save_dir}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 7: Style-Stratified Evaluation on Test Split (Styles 0, 1, 2, Overall)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "import json\n",
                "import shutil\n",
                "import torch\n",
                "\n",
                "REPO_DIR = '/content/genai-restoration-studio' if os.path.exists('/content/genai-restoration-studio') else os.getcwd()\n",
                "PROJECT_DIR = '/content/drive/MyDrive/GenAI-A1'\n",
                "if REPO_DIR not in sys.path:\n",
                "    sys.path.insert(0, REPO_DIR)\n",
                "os.chdir(REPO_DIR)\n",
                "\n",
                "from models.cgan import StyleConditionedUNetGenerator\n",
                "from evaluation.benchmark_cgan import run_cgan_benchmark\n",
                "\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "print(f\"Using device: {device}\")\n",
                "\n"                "# Resolve manifest and local data dirs\n",
                "manifest_candidates = [\n",
                "    os.path.join(PROJECT_DIR, 'manifests'),\n",
                "    os.path.join(PROJECT_DIR, 'configs/manifests'),\n",
                "    os.path.join(REPO_DIR, 'configs/manifests'),\n",
                "    os.path.join(REPO_DIR, 'manifests')\n",
                "]\n",
                "MANIFEST_DIR = next(mc for mc in manifest_candidates if os.path.exists(os.path.join(mc, 'fs2k_test_manifest.json')))\n",
                "\n",
                "LOCAL_DATA_DIR = '/content/local_data/FS2K'\n",
                "if not os.path.exists(os.path.join(LOCAL_DATA_DIR, 'photo')):\n",
                "    drive_folder_candidates = [\n",
                "        os.path.join(PROJECT_DIR, 'raw/FS2K/FS2K'),\n",
                "        os.path.join(PROJECT_DIR, 'raw/FS2K'),\n",
                "        os.path.join(PROJECT_DIR, 'data/FS2K')\n",
                "    ]\n",
                "    for fc in drive_folder_candidates:\n",
                "        if os.path.exists(os.path.join(fc, 'photo')):\n",
                "            LOCAL_DATA_DIR = fc\n",
                "            break\n",
                "\n",
                "print(f\"Manifest Dir:   {MANIFEST_DIR}\")\n",
                "print(f\"FS2K Data Root: {LOCAL_DATA_DIR}\")\n",
                "\n",
                "# Load generator architecture configuration\n",
                "optuna_candidates = [\n",
                "    os.path.join(PROJECT_DIR, 'checkpoints/task4/optuna_best_params.json'),\n",
                "    os.path.join(REPO_DIR, 'checkpoints/task4/optuna_best_params.json')\n",
                "]\n",
                "eval_params = {}\n",
                "for op in optuna_candidates:\n",
                "    if os.path.exists(op):\n",
                "        with open(op, 'r', encoding='utf-8') as f:\n",
                "            eval_params = json.load(f)\n",
                "        print(f\"Loaded architecture params from {op}\")\n",
                "        break\n",
                "\n",
                "best_g = StyleConditionedUNetGenerator(\n",
                "    in_channels=3,\n",
                "    out_channels=3,\n",
                "    num_styles=3,\n",
                "    emb_dim=int(eval_params.get('emb_dim', 32)),\n",
                "    emb_channels=16,\n",
                "    base_channels=int(eval_params.get('base_channels_g', 64)),\n",
                "    dropout_rate=float(eval_params.get('dropout_rate', 0.5))\n",
                ").to(device)\n",
                "\n",
                "# Find and strictly load checkpoint\n",
                "ckpt_candidates = [\n",
                "    os.path.join(PROJECT_DIR, 'checkpoints/task4/best_cgan_generator.pth'),\n",
                "    os.path.join(REPO_DIR, 'checkpoints/task4/best_cgan_generator.pth'),\n",
                "    os.path.join(PROJECT_DIR, 'checkpoints/task4/best_generator.pth'),\n",
                "    os.path.join(REPO_DIR, 'checkpoints/task4/best_generator.pth')\n",
                "]\n",
                "\n",
                "target_ckpt = None\n",
                "for cp in ckpt_candidates:\n",
                "    if os.path.exists(cp):\n",
                "        target_ckpt = cp\n",
                "        break\n",
                "\n",
                "if target_ckpt is None:\n",
                "    raise FileNotFoundError(\n",
                "        \"FATAL: No Task 4 generator checkpoint found! \"\n",
                "        \"Expected 'best_cgan_generator.pth' under Drive or local checkpoints directory. \"\n",
                "        \"Run Step 6 to train or verify Drive mount.\"\n",
                "    )\n",
                "\n",
                "print(f\"\\n[CHECKPOINT LOADED] Loading weights strictly from: {target_ckpt}\")\n",
                "ckpt = torch.load(target_ckpt, map_location=device)\n",
                "state_dict = ckpt['generator_state_dict'] if isinstance(ckpt, dict) and 'generator_state_dict' in ckpt else ckpt\n",
                "best_g.load_state_dict(state_dict, strict=True)\n",
                "best_g.eval()\n",
                "\n",
                "if isinstance(ckpt, dict):\n",
                "    saved_ep = ckpt.get('epoch', 'N/A')\n",
                "    saved_metrics = ckpt.get('val_metrics', {})\n",
                "    print(f\"  Checkpoint Epoch: {saved_ep} | Stored Val PSNR: {saved_metrics.get('psnr', 'N/A')} dB | SSIM: {saved_metrics.get('ssim', 'N/A')}\")\n",
                "\n",
                "# Run full test benchmark\n",
                "out_dir = \"artifacts/evaluation_task4\"\n",
                "benchmark_results = run_cgan_benchmark(\n",
                "    generator=best_g,\n",
                "    manifest_path=MANIFEST_DIR,\n",
                "    fs2k_root=LOCAL_DATA_DIR,\n",
                "    device=str(device),\n",
                "    output_dir=out_dir,\n",
                "    num_visualizations=12\n",
                ")\n",
                "\n",
                "# Sync evaluation artifacts to Drive\n",
                "drive_art_dir = os.path.join(PROJECT_DIR, 'artifacts/evaluation_task4')\n",
                "os.makedirs(drive_art_dir, exist_ok=True)\n",
                "if os.path.exists(out_dir):\n",
                "    for root, dirs, files in os.walk(out_dir):\n",
                "        rel = os.path.relpath(root, out_dir)\n",
                "        target_root = os.path.join(drive_art_dir, rel) if rel != '.' else drive_art_dir\n",
                "        os.makedirs(target_root, exist_ok=True)\n",
                "        for f in files:\n",
                "            shutil.copy2(os.path.join(root, f), os.path.join(target_root, f))\n",
                "print(f\"[SUCCESS] Evaluation report and figures synchronized to Drive: {drive_art_dir}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 8: Qualitative Visualization Across All 3 Styles"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "import json\n",
                "import shutil\n",
                "import torch\n",
                "import matplotlib.pyplot as plt\n",
                "from PIL import Image\n",
                "\n",
                "REPO_DIR = '/content/genai-restoration-studio' if os.path.exists('/content/genai-restoration-studio') else os.getcwd()\n",
                "PROJECT_DIR = '/content/drive/MyDrive/GenAI-A1'\n",
                "if REPO_DIR not in sys.path:\n",
                "    sys.path.insert(0, REPO_DIR)\n",
                "os.chdir(REPO_DIR)\n",
                "\n",
                "from models.cgan import StyleConditionedUNetGenerator\n",
                "from data.fs2k import get_fs2k_dataloaders\n",
                "\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "\n",
                "# Re-establish test_loader and best_g if missing from memory\n",
                "if 'test_loader' not in globals():\n",
                "    manifest_candidates = [\n",
                "        os.path.join(PROJECT_DIR, 'manifests'),\n",
                "        os.path.join(PROJECT_DIR, 'configs/manifests'),\n",
                "        os.path.join(REPO_DIR, 'configs/manifests'),\n",
                "        os.path.join(REPO_DIR, 'manifests')\n",
                "    ]\n",
                "    m_dir = next(mc for mc in manifest_candidates if os.path.exists(os.path.join(mc, 'fs2k_test_manifest.json')))\n",
                "    local_data = '/content/local_data/FS2K' if os.path.exists('/content/local_data/FS2K') else os.path.join(PROJECT_DIR, 'raw/FS2K/FS2K')\n",
                "    _, _, test_loader = get_fs2k_dataloaders(m_dir, local_data, batch_size=16, num_workers=0)\n",
                "\n",
                "if 'best_g' not in globals():\n",
                "    optuna_candidates = [\n",
                "        os.path.join(PROJECT_DIR, 'checkpoints/task4/optuna_best_params.json'),\n",
                "        os.path.join(REPO_DIR, 'checkpoints/task4/optuna_best_params.json')\n",
                "    ]\n",
                "    p = {}\n",
                "    for op in optuna_candidates:\n",
                "        if os.path.exists(op):\n",
                "            with open(op, 'r') as f:\n",
                "                p = json.load(f)\n",
                "            break\n",
                "    best_g = StyleConditionedUNetGenerator(\n",
                "        in_channels=3, out_channels=3, num_styles=3,\n",
                "        emb_dim=int(p.get('emb_dim', 32)),\n",
                "        emb_channels=16,\n",
                "        base_channels=int(p.get('base_channels_g', 64)),\n",
                "        dropout_rate=float(p.get('dropout_rate', 0.5))\n",
                "    ).to(device)\n",
                "    ckpt_candidates = [\n",
                "        os.path.join(PROJECT_DIR, 'checkpoints/task4/best_cgan_generator.pth'),\n",
                "        os.path.join(REPO_DIR, 'checkpoints/task4/best_cgan_generator.pth')\n",
                "    ]\n",
                "    target_ckpt = next(cp for cp in ckpt_candidates if os.path.exists(cp))\n",
                "    ckpt = torch.load(target_ckpt, map_location=device)\n",
                "    best_g.load_state_dict(ckpt['generator_state_dict'] if 'generator_state_dict' in ckpt else ckpt, strict=True)\n",
                "\n",
                "# 1. Display benchmark comparisons if generated\n",
                "comp_paths = [\n",
                "    'artifacts/evaluation_task4/figures/test_synthesis_comparisons.png',\n",
                "    os.path.join(PROJECT_DIR, 'artifacts/evaluation_task4/figures/test_synthesis_comparisons.png')\n",
                "]\n",
                "for cp in comp_paths:\n",
                "    if os.path.exists(cp):\n",
                "        plt.figure(figsize=(10, 14))\n",
                "        img = Image.open(cp)\n",
                "        plt.imshow(img)\n",
                "        plt.axis('off')\n",
                "        plt.title(\"Test Set Syntheses: Photo | Ground Truth Sketch | cGAN Generated\", fontsize=12)\n",
                "        plt.show()\n",
                "        break\n",
                "\n",
                "# 2. Multi-style transfer matrix: same input photos rendered in Style 0, Style 1, Style 2\n",
                "best_g.eval()\n",
                "with torch.no_grad():\n",
                "    sample_b = next(iter(test_loader))\n",
                "    test_p = sample_b['photo'][:4].to(device)\n",
                "    \n",
                "    fig, axes = plt.subplots(4, 4, figsize=(12, 12))\n",
                "    for row in range(4):\n",
                "        p_np = ((test_p[row].permute(1, 2, 0).cpu().numpy() * 0.5) + 0.5).clip(0, 1)\n",
                "        axes[row, 0].imshow(p_np)\n",
                "        axes[row, 0].set_title(f\"Input Photo {row+1}\", fontsize=9)\n",
                "        axes[row, 0].axis('off')\n",
                "        \n",
                "        for st_idx in range(3):\n",
                "            st_t = torch.tensor([st_idx], dtype=torch.long, device=device)\n",
                "            fake_st = best_g(test_p[row:row+1], st_t)\n",
                "            fake_np = ((fake_st[0].permute(1, 2, 0).cpu().numpy() * 0.5) + 0.5).clip(0, 1)\n",
                "            axes[row, st_idx + 1].imshow(fake_np)\n",
                "            axes[row, st_idx + 1].set_title(f\"Style {st_idx}\", fontsize=9)\n",
                "            axes[row, st_idx + 1].axis('off')\n",
                "            \n",
                "    plt.tight_layout()\n",
                "    matrix_out = 'artifacts/evaluation_task4/figures/multistyle_transfer_matrix.png'\n",
                "    os.makedirs(os.path.dirname(matrix_out), exist_ok=True)\n",
                "    plt.savefig(matrix_out, dpi=150, bbox_inches='tight')\n",
                "    plt.show()\n",
                "\n",
                "    # Sync to Drive\n",
                "    drive_fig_dir = os.path.join(PROJECT_DIR, 'artifacts/evaluation_task4/figures')\n",
                "    os.makedirs(drive_fig_dir, exist_ok=True)\n",
                "    shutil.copy2(matrix_out, os.path.join(drive_fig_dir, 'multistyle_transfer_matrix.png'))"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 9: Generator-Only ONNX Export & Parity Verification"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "import json\n",
                "import shutil\n",
                "import torch\n",
                "\n",
                "REPO_DIR = '/content/genai-restoration-studio' if os.path.exists('/content/genai-restoration-studio') else os.getcwd()\n",
                "PROJECT_DIR = '/content/drive/MyDrive/GenAI-A1'\n",
                "if REPO_DIR not in sys.path:\n",
                "    sys.path.insert(0, REPO_DIR)\n",
                "os.chdir(REPO_DIR)\n",
                "\n",
                "from models.cgan import StyleConditionedUNetGenerator\n",
                "from models.onnx_export_cgan import export_cgan_generator_to_onnx, verify_cgan_onnx_numerical_equivalence\n",
                "\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "\n",
                "if 'best_g' not in globals():\n",
                "    optuna_candidates = [\n",
                "        os.path.join(PROJECT_DIR, 'checkpoints/task4/optuna_best_params.json'),\n",
                "        os.path.join(REPO_DIR, 'checkpoints/task4/optuna_best_params.json')\n",
                "    ]\n",
                "    p = {}\n",
                "    for op in optuna_candidates:\n",
                "        if os.path.exists(op):\n",
                "            with open(op, 'r') as f:\n",
                "                p = json.load(f)\n",
                "            break\n",
                "    best_g = StyleConditionedUNetGenerator(\n",
                "        in_channels=3, out_channels=3, num_styles=3,\n",
                "        emb_dim=int(p.get('emb_dim', 32)),\n",
                "        emb_channels=16,\n",
                "        base_channels=int(p.get('base_channels_g', 64)),\n",
                "        dropout_rate=float(p.get('dropout_rate', 0.5))\n",
                "    ).to(device)\n",
                "    ckpt_candidates = [\n",
                "        os.path.join(PROJECT_DIR, 'checkpoints/task4/best_cgan_generator.pth'),\n",
                "        os.path.join(REPO_DIR, 'checkpoints/task4/best_cgan_generator.pth')\n",
                "    ]\n",
                "    target_ckpt = next(cp for cp in ckpt_candidates if os.path.exists(cp))\n",
                "    ckpt = torch.load(target_ckpt, map_location=device)\n",
                "    best_g.load_state_dict(ckpt['generator_state_dict'] if 'generator_state_dict' in ckpt else ckpt, strict=True)\n",
                "\n",
                "onnx_local_path = os.path.join(REPO_DIR, 'checkpoints/task4/cgan_generator.onnx')\n",
                "onnx_drive_path = os.path.join(PROJECT_DIR, 'checkpoints/task4/cgan_generator.onnx')\n",
                "\n",
                "# Export using PyTorch opset 18, dynamo=False, embedded weights\n",
                "export_cgan_generator_to_onnx(best_g, onnx_local_path, opset_version=18)\n",
                "\n",
                "# Numerical parity check with ONNX Runtime\n",
                "parity_report = verify_cgan_onnx_numerical_equivalence(\n",
                "    generator=best_g,\n",
                "    onnx_path=onnx_local_path,\n",
                "    atol=1e-4\n",
                ")\n",
                "\n",
                "assert parity_report['equivalent'] is True, \"ONNX numerical parity check failed!\"\n",
                "assert parity_report['onnx_size_mb'] > 10.0, f\"ONNX file size ({parity_report['onnx_size_mb']:.2f} MB) is suspiciously small!\"\n",
                "\n",
                "# Copy ONNX to Drive\n",
                "os.makedirs(os.path.dirname(onnx_drive_path), exist_ok=True)\n",
                "shutil.copy2(onnx_local_path, onnx_drive_path)\n",
                "\n",
                "print(f\"\\n[ONNX SUCCESS] Standalone ONNX model exported and verified ({parity_report['onnx_size_mb']:.2f} MB).\")\n",
                "print(f\"  Local Path: {onnx_local_path}\")\n",
                "print(f\"  Drive Path: {onnx_drive_path}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### Step 10: Sync All Task 4 Artifacts to Google Drive & Final Verification"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import os\n",
                "import sys\n",
                "import shutil\n",
                "\n",
                "REPO_DIR = '/content/genai-restoration-studio' if os.path.exists('/content/genai-restoration-studio') else os.getcwd()\n",
                "PROJECT_DIR = '/content/drive/MyDrive/GenAI-A1'\n",
                "\n",
                "DRIVE_CKPT_DIR = os.path.join(PROJECT_DIR, 'checkpoints/task4')\n",
                "DRIVE_EVAL_DIR = os.path.join(PROJECT_DIR, 'artifacts/evaluation_task4')\n",
                "\n",
                "os.makedirs(DRIVE_CKPT_DIR, exist_ok=True)\n",
                "os.makedirs(DRIVE_EVAL_DIR, exist_ok=True)\n",
                "\n",
                "# Copy checkpoints, ONNX, and Optuna params\n",
                "local_ckpt_dir = os.path.join(REPO_DIR, 'checkpoints/task4')\n",
                "if os.path.exists(local_ckpt_dir):\n",
                "    for root, dirs, files in os.walk(local_ckpt_dir):\n",
                "        rel = os.path.relpath(root, local_ckpt_dir)\n",
                "        dest_root = os.path.join(DRIVE_CKPT_DIR, rel) if rel != '.' else DRIVE_CKPT_DIR\n",
                "        os.makedirs(dest_root, exist_ok=True)\n",
                "        for f in files:\n",
                "            shutil.copy2(os.path.join(root, f), os.path.join(dest_root, f))\n",
                "\n",
                "# Copy evaluation JSON and figures\n",
                "local_eval_dir = os.path.join(REPO_DIR, 'artifacts/evaluation_task4')\n",
                "if os.path.exists(local_eval_dir):\n",
                "    for root, dirs, files in os.walk(local_eval_dir):\n",
                "        rel = os.path.relpath(root, local_eval_dir)\n",
                "        dest_root = os.path.join(DRIVE_EVAL_DIR, rel) if rel != '.' else DRIVE_EVAL_DIR\n",
                "        os.makedirs(dest_root, exist_ok=True)\n",
                "        for f in files:\n",
                "            shutil.copy2(os.path.join(root, f), os.path.join(dest_root, f))\n",
                "\n",
                "print(\"\\n\" + \"=\" * 60)\n",
                "print(\"GOOGLE DRIVE TASK 4 ARTIFACT VERIFICATION\")\n",
                "print(\"=\" * 60)\n",
                "\n",
                "print(f\"\\nCheckpoints in {DRIVE_CKPT_DIR}:\")\n",
                "for f in sorted(os.listdir(DRIVE_CKPT_DIR)):\n",
                "    fp = os.path.join(DRIVE_CKPT_DIR, f)\n",
                "    if os.path.isfile(fp):\n",
                "        size_mb = os.path.getsize(fp) / (1024 * 1024)\n",
                "        print(f\"  - {f} ({size_mb:.2f} MB)\")\n",
                "    else:\n",
                "        print(f\"  - [DIR] {f}/\")\n",
                "\n",
                "print(f\"\\nEvaluation Artifacts in {DRIVE_EVAL_DIR}:\")\n",
                "for root, dirs, files in os.walk(DRIVE_EVAL_DIR):\n",
                "    rel = os.path.relpath(root, DRIVE_EVAL_DIR)\n",
                "    for f in sorted(files):\n",
                "        fp = os.path.join(root, f)\n",
                "        size_mb = os.path.getsize(fp) / (1024 * 1024)\n",
                "        print(f\"  - {os.path.join(rel, f) if rel != '.' else f} ({size_mb:.2f} MB)\")\n",
                "\n",
                "# Assert critical files exist on Drive\n",
                "assert os.path.exists(os.path.join(DRIVE_CKPT_DIR, 'best_cgan_generator.pth')), \"Missing best_cgan_generator.pth on Drive!\"\n",
                "assert os.path.exists(os.path.join(DRIVE_CKPT_DIR, 'cgan_generator.onnx')), \"Missing cgan_generator.onnx on Drive!\"\n",
                "assert os.path.exists(os.path.join(DRIVE_EVAL_DIR, 'cgan_benchmark_results.json')), \"Missing cgan_benchmark_results.json on Drive!\"\n",
                "\n",
                "print(\"\\n[SUCCESS] Milestone 4 complete! All artifacts securely persisted on Google Drive.\")"
            ]
        }
    ]

    notebook_dict = {
        "cells": cells,
        "metadata": {
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }

    output_path = "notebooks/05_task4_cgan_sketch.ipynb"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(notebook_dict, f, indent=2)

    print(f"Created notebook at {output_path}")

if __name__ == "__main__":
    build_task4_notebook()
